### ISSUE TITLE
[Crash]: Echo chest does not work with create chutes.

### ISSUE THREAD

**Issue by Nekobrenna** [Fuzss/echochest#2]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

V4.0.1-1.19.2-Fabric

### Notes (Required)

1. Place Echo Chest.
2. Attach chute to the chest from the create mod for fabric. 
3. The world crashes and continues to crash on loading.

### Crash Report (Required)

https://gist.github.com/Nekobrenna/f066ce044c40fc53c625a7049f4518a8

**Comment by YumatanGames** [comment]
It also crashes with nether chests, just tested!

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.2.
