### ISSUE TITLE
[Bug]: Game crash upon pick block in creative mode on both echo and nether chests

### ISSUE THREAD

**Issue by Nekobrenna** [Fuzss/echochest#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.2

### Notes (Required)

In creative mode if you try to pick block either the echo chest or the nether chest, it will crash the game.

### latest.log (Optional)

https://gist.github.com/Nekobrenna/530125438fc08c7479072a8a500c25b3

**Comment by Fuzss** [comment]
Report this to Ender Tap.
