### ISSUE TITLE
[Bug]: Mod echochest requires puzzleslib 20.4.11 or above, But 20.4.11 for Neoforge is not on Curseforge

### ISSUE THREAD

**Issue by ModernGamingWorld** [Fuzss/echochest#8]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.0

### Minimal Setup (Required)

Yes

### Notes (Required)

Modpack Developers can't use your mod if the lib mod version is wrong

### latest.log (Required)

https://gist.github.com/ModernGamingWorld/ac8743db0532a9c72b60d3cf94c020d9

**Comment by Fuzss** [comment]
Thanks, new Puzzles Lib is out.
